[theme]
primaryColor = "#ffcc00"
backgroundColor = "#1e3c72"
secondaryBackgroundColor = "#2a5298"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
